### ISSUE TITLE
Adguard doesn't pause. misleading menus and messages.

### ISSUE THREAD

**Issue by hazarek** [AdguardTeam/AdGuardForSafari#300]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

AdGuard for Safari version: 1.6.2
Safari 13.0.3
macOS Catalina 10.15.1

### Expected Behavior
it should stop when I press "pause adguard".
<img width="204" alt="cap 2" src="https://user-images.githubusercontent.com/36481442/69480658-8dd97a00-0e1a-11ea-8ba4-412187c153d7.png">

### Actual Behavior
Adguard doesn't pause. when i press "Pause Adguard"

### Additional Information
misleading message;
<img width="275" alt="cap 3" src="https://user-images.githubusercontent.com/36481442/69481059-c713e900-0e1e-11ea-898f-610e59ead8fc.png">

It stops when I uncheck "enable content blockers" in Safari site settings.
<img width="370" alt="cap 1" src="https://user-images.githubusercontent.com/36481442/69481086-f9254b00-0e1e-11ea-8a92-f1936ecf291b.png">

Misleading menu checkbox. AdGuard is already active.
<img width="218" alt="cap 4" src="https://user-images.githubusercontent.com/36481442/69481148-9f715080-0e1f-11ea-861a-3e59cdade091.png">

AdGuard says it is both "disabled" and "enabled" at the same time.
<img width="258" alt="cap" src="https://user-images.githubusercontent.com/36481442/69481178-f6772580-0e1f-11ea-9feb-7c2560be61a4.png">

**Comment by ameshkov** [comment]
> Adguard doesn't pause. when i press "Pause Adguard"

What do you mean it does not pause? Does it continue to block anything in your case?

**Comment by hazarek** [comment]
> What do you mean it does not pause? Does it continue to block anything in your case?
@ameshkov 

Yes, it continue to block filters. It stops then i uncheck "enable content blockers"

**Comment by ameshkov** [comment]
Hm, yep, this is a legit bug

**Comment by hazarek** [comment]
I wrote the wrong safari version. I fixed it. 

AdGuard for Safari version: 1.6.2
Safari 13.0.3
macOS Catalina 10.15.1

**Comment by einfallstoll** [comment]
I noticed this in 1.7.4. Regression?

**Comment by zecanard** [comment]
I’ve seen this happen every once in a while, even before 1.7.4. Unfortunately, I haven’t been able to determine exact steps to reproduce.

**Comment by einfallstoll** [comment]
@zecanard I can start and pause AdGuard again, but it would still happen. I didn't restart Safari yet, so if I get some debugging instructions I might be able to track down the issue.

**Comment by zzebrum** [comment]
@einfallstoll @zecanard can you collect logs? Click on the AdGuard icon in the tray menu and then Export logs and system info. send the archive to apple[at]adguard[dot]com

**Comment by einfallstoll** [comment]
@zzebrum done

**Comment by zzebrum** [comment]
@einfallstoll got your logs, thanks

@Mizzick please take a look, logs are in ncloud.

**Comment by zzebrum** [comment]
it seems to be working now, please, reopen if needed
